#!/bin/bash

. /etc/sysconfig/logstash

cd /var/lib/logstash
FULLNAME="$0"
JAVA_ARGS="-Xms${LOGSTASH_MEM_MIN}M -Xmx${LOGSTASH_MEM_MAX}M"
ARGS="-f ${LOGSTASH_CONFIG}"

exec -a "${FULLNAME}" java $JAVA_ARGS -cp /etc/logstash/:/usr/share/logstash/logstash-${LOGSTASH_VERSION}-monolithic.jar logstash.runner agent $ARGS

